import jnumpy as np

def jl_not(x: bool) -> bool: ...
def int_add(x: int, y: int) -> int: ...
def float_add(x: float, y: float) -> float: ...
def complex_mul_two(x: complex) -> complex: ...
def str_concat(x: str, y: str) -> str: ...
def tuple_return(x: int, y: str) -> tuple[int, str]: ...
def mat_mul(x: np.ndarray, y: np.ndarray) -> np.ndarray: ...
def set_zero(x: np.ndarray) -> None: ...
def jl_fft(x: np.ndarray) -> np.ndarray: ...
